global:
  name: consul
  image: "hashicorp/consul-enterprise:${consul_version}"
  imageK8S: docker.mirror.hashicorp.services/hashicorp/consul-k8s-control-plane:${consul_helm_chart_version}
  imageConsulDataplane: "hashicorp/consul-dataplane:1.0.0"
  enableConsulNamespaces: true
  enterpriseLicense:
    secretName: 'consul-ent-license'
    secretKey: 'key'
    enableLicenseAutoload: true
  datacenter: ${datacenter}
  peering:
    enabled: true
  adminPartitions:
    enabled: true
    name: ${partition}

  # TLS configures whether Consul components use TLS.
  tls:
    enabled: true
  acls:
    manageSystemACLs: true
  %{~ if node_selector != "" ~}
    nodeSelector: |
      ${node_selector}
  %{~ endif ~}
  metrics:
    enabled: true
    enableGatewayMetrics: true
server:
  replicas: 3
  bootstrapExpect: 3
  exposeService:
    # When enabled, deploys a Kubernetes Service to reach the Consul servers.
    # @type: boolean
    enabled: true
    type: LoadBalancer
    annotations: |
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
  %{~ if node_selector != "" ~}
  nodeSelector: |
    ${node_selector}
  %{~ endif ~}
 
  extraConfig: |
    {
      "log_level": "TRACE"
    }

dns:
  enabled: true
  enableRedirection: true

webhookCertManager:
  %{~ if node_selector != "" ~}
  nodeSelector: |
    ${node_selector}
  %{~ endif ~}

connectInject:
  enabled: true
  default: false
  transparentProxy:
    defaultEnabled: false
  consulNamespaces:
    mirroringK8S: true
  %{~ if node_selector != "" ~}
  nodeSelector: |
    ${node_selector}
  %{~ endif ~}
  metrics:
    defaultEnabled: true # by default, this inherits from the value global.metrics.enabled
    defaultEnableMerging: true
    # defaultPrometheusScrapePort: 20200
    # defaultPrometheusScrapePath: "/metrics"
    # defaultMergedMetricsPort: 20100

meshGateway:
  enabled: true
  replicas: 1
  service:
    enabled: true
    type: LoadBalancer
    annotations: |
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
  %{~ if node_selector != "" ~}
  nodeSelector: |
    ${node_selector}
  %{~ endif ~}
ingressGateways:
  enabled: true
  defaults:
    replicas: 1
    %{~ if node_selector != "" ~}
    nodeSelector: |
      ${node_selector}
    %{~ endif ~}
  gateways:
    - name: ingress-gateway
      service:
        type: LoadBalancer

ui:
  enabled: true
  service:
    enabled: true
    type: LoadBalancer
  metrics:
    enabled: true # by default, this inherits from the value global.metrics.enabled
    provider: "prometheus"
    baseURL: http://prometheus-server.default.svc.cluster.local