apiVersion: consul.hashicorp.com/v1alpha1         # required
kind: SamenessGroup                               # required
metadata:
  name: apps-sameness-group
spec:
  defaultForFailover: true
  members:
    - partition: app2
    - peer: dc1-app1
