# https://github.com/hashicorp/consul-k8s/blob/main/charts/consul/values.yaml
global:
  name: team2
  enabled: false
  datacenter: usw2
  image: "hashicorp/consul-enterprise:1.14.3"
  imageK8S: docker.mirror.hashicorp.services/hashicorp/consul-k8s-control-plane:1.0.2
  imageConsulDataplane: "hashicorp/consul-dataplane:1.0.0"
  enableConsulNamespaces: true
  adminPartitions:
    enabled: true
    name: "pci"
  peering:
    enabled: true
  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: consul-bootstrap-token
      secretKey: token
  tls:
    enabled: true

server:
  enabled: false

externalServers:
  enabled: true
  hosts: ["usw2.private.consul.328306de-41b8-43a7-9c38-ca8d89d06b07.aws.hashicorp.cloud"]
  httpsPort: 443
  grpcPort: 8502
  useSystemRoots: true
  k8sAuthMethodHost: https://4966F02AFD05DE4C182A3C104EEE98D6.gr7.us-west-2.eks.amazonaws.com
dns:
  enabled: true
  enableRedirection: true
  clusterIP: 172.21.128.87 # Needed to configure kube-dns forwarding
connectInject:
  enabled: true
  transparentProxy:
    defaultEnabled: true
  metrics:
    defaultEnabled: true # by default, this inherits from the value global.metrics.enabled
    defaultEnableMerging: true
  consulNamespaces:
    mirroringK8S: true
  consulNode:
    meta: 
      node: "team2-agentless-node"
syncCatalog:
  enabled: true
  toConsul: false
  toK8S: true
meshGateway:
  enabled: true
  replicas: 1
ingressGateways:
  enabled: true
  defaults:
    replicas: 1
  gateways:
    - name: ingress-gateway
      service:
        type: LoadBalancer

