# https://github.com/hashicorp/consul-k8s/blob/main/charts/consul/values.yaml
global:
  name: ${NAME_PREFIX}
  enabled: false
  datacenter: ${DATACENTER}
  image: "hashicorp/consul-enterprise:1.14.3"
  imageK8S: docker.mirror.hashicorp.services/hashicorp/consul-k8s-control-plane:1.0.2
  imageConsulDataplane: "hashicorp/consul-dataplane:1.0.0"
  enableConsulNamespaces: true
  adminPartitions:
    enabled: true
    name: "otk"
  peering:
    enabled: true
  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: consul-bootstrap-token
      secretKey: token
  tls:
    enabled: true
    caCert:
      secretName: consul-ca-cert
      secretKey: tls.crt
server:
  enabled: false

externalServers:
  enabled: true
  hosts: ${RETRY_JOIN}
  httpsPort: 443
  grpcPort: 8502
  useSystemRoots: false
  k8sAuthMethodHost: ${KUBE_API_URL}
dns:
  enabled: true
  enableRedirection: true
  clusterIP: ${CONSUL_DNS_CLUSTER_IP} # Needed to configure kube-dns forwarding
connectInject:
  enabled: true
  transparentProxy:
    defaultEnabled: true
  metrics:
    defaultEnabled: true # by default, this inherits from the value global.metrics.enabled
    defaultEnableMerging: true
  consulNamespaces:
    mirroringK8S: true
  consulNode:
    meta: 
      node: "${NAME_PREFIX}-agentless-node"
syncCatalog:
  enabled: true
  toConsul: false
  toK8S: true
meshGateway:
  enabled: true
  replicas: 1
ingressGateways:
  enabled: true
  defaults:
    replicas: 1
  gateways:
    - name: ingress-gateway
      service:
        type: LoadBalancer
