apiVersion: consul.hashicorp.com/v1alpha1
kind: ExportedServices
metadata:
  name: default ## The name of the partition containing the service
  namespace: default
spec:
  services:
    - name: mesh-gateway
      namespace: default
      consumers:
        - partition: default
