apiVersion: consul.hashicorp.com/v1alpha1
kind: ExportedServices
metadata:
  name: api ## The name of the partition containing the service
  namespace: default
spec:
  services:
    - name: mesh-gateway
      namespace: default
      consumers:
        - partition: web
    - name: api ## The name of the service you want to export
      namespace: api
      consumers:
        - partition: web # The name of the partition that receives the service
