apiVersion: v1
kind: ServiceAccount
metadata:
  name:   fortio-server-defaults
  namespace: fortio-consul-default-tcp
---
apiVersion: v1
kind: Service
metadata:
  name:   fortio-server-defaults
  namespace: fortio-consul-default-tcp
spec:
  selector:
    app:   fortio-server-defaults
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: grpc
    port: 8079
    targetPort: 8079
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fortio-consul-default-tcp
  labels:
    app:   fortio-server-defaults
  name:   fortio-server-defaults
spec:
  replicas: 1
  selector:
    matchLabels:
      app:   fortio-server-defaults
  template:
    metadata:
      namespace: fortio-consul-default-tcp
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/transparent-proxy': 'true'
      labels:
        app:   fortio-server-defaults
    spec:
      containers:
      - name:   fortio-server-defaults
        image: fortio/fortio:latest_release
        env:       
        ports:
        - containerPort: 8080
          name: http-fortio
        - containerPort: 8079
          name: grpc-ping        
      serviceAccountName:   fortio-server-defaults
      nodeSelector:
        nodegroup: services