---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: api
  namespace: default
spec:
  connectTimeout: 0s
  failover:
    '*':
      targets:
        - partition: app1
          namespace: default
          service: api
        #- namespace: westus2-3
        # - peer: presto-cluster-use1-app1
        #   namespace: default
        #   service: api

