apiVersion: v1
kind: ServiceAccount
metadata:
  name:   fortio-server-defaults-grpc
  namespace: fortio-consul-optimized
---
apiVersion: v1
kind: Service
metadata:
  name:   fortio-server-defaults-grpc
  namespace: fortio-consul-optimized
spec:
  selector:
    app:   fortio-server-defaults-grpc
  ports:
  - port: 8079
    targetPort: 8079
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fortio-consul-optimized
  labels:
    app:   fortio-server-defaults-grpc
  name:   fortio-server-defaults-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app:   fortio-server-defaults-grpc
  template:
    metadata:
      namespace: fortio-consul-optimized
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/transparent-proxy': 'true'
        'consul.hashicorp.com/consul-envoy-proxy-concurrency': '2'
        'consul.hashicorp.com/sidecar-proxy-cpu-limit': '750m' # 50% of a vCPU
        'consul.hashicorp.com/sidecar-proxy-cpu-request': '750m'
        'consul.hashicorp.com/sidecar-proxy-memory-limit': '100Mi'
        'consul.hashicorp.com/sidecar-proxy-memory-request': '100Mi'
      labels:
        app:   fortio-server-defaults-grpc
    spec:
      containers:
      - name:   fortio-server-defaults-grpc
        image: fortio/fortio:latest_release
        env:       
        ports:
        - containerPort: 8079
          name: grpc-ping        
      serviceAccountName:   fortio-server-defaults-grpc
      nodeSelector:
        nodegroup: services