apiVersion: consul.hashicorp.com/v1alpha1
kind: PeeringDialer
metadata:
  name: presto-cluster-use1-app1 ## The name of the peer you want to connect to
  namespace: consul
spec:
  peer:
    secret:
      name: "peering-token-presto-cluster-usw2-app1"
      key: "data"
      backend: "kubernetes"
