---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: fortio-server-defaults
  namespace: fortio-consul-l7
spec:
  destination:
    name: fortio-server-defaults
    namespace: fortio-consul-l7
  sources:
    - name: fortio-client
      permissions:
      - action: allow
        http:
          header:
          - name: MY_CUSTOM_REQ_HEADER
            present: true
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: fortio-server-defaults-grpc
  namespace: fortio-consul-l7
spec:
  destination:
    name: fortio-server-defaults-grpc
    namespace: fortio-consul-l7
  sources:
    - name: fortio-client
      permissions:
      - action: allow
        http:
          header:
          - name: MY_CUSTOM_REQ_HEADER
            present: true