apiVersion: consul.hashicorp.com/v1alpha1
kind: ExportedServices
metadata:
  name: app1 ## The name of the partition containing the service
spec:
  services:
    - name: mesh-gateway
      namespace: default
      consumers:
        - peer: dc2-app2
    - name: api ## The name of the service you want to export
      namespace: default
      consumers:
        - peer: dc2-app2 # The name of the partition that receives the service
