apiVersion: consul.hashicorp.com/v1alpha1
kind: PeeringAcceptor
metadata:
  name: app2-default ## West Peer Name:  name of the peer you want to connect to
  namespace: consul     ## k8s namespace
spec:
  peer:
    secret:
      name: "peering-token-app2-default"
      key: "data"
      backend: "kubernetes"