global:
  enabled: false
  logLevel: "debug"
  name: aks0
  datacenter: consul0-eastus
  image: "hashicorp/consul-enterprise:1.14.0-ent"
  imageK8S: docker.mirror.hashicorp.services/hashicorp/consul-k8s-control-plane:1.0.0
  imageConsulDataplane: "hashicorp/consul-dataplane:1.0.0"

  enableConsulNamespaces: true
  adminPartitions:
    enabled: true
    name: "shared"
  peering:
    enabled: true
  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: consul-bootstrap-acl-token
      secretKey: token
  tls:
    enabled: true
    caCert:
      secretName: consul-ca-cert
      secretKey: tls.crt

externalServers:
  enabled: true
  hosts: ["172.16.2.11"]
  tlsServerName: "server.consul0-eastus.consul"
  httpsPort: 8501
  grpcPort: 8502
  useSystemRoots: false
  k8sAuthMethodHost: https://aks-d723b529.hcp.eastus.azmk8s.io:443

server:
  enabled: false

connectInject:
  transparentProxy:
    defaultEnabled: true
  enabled: true
  default: true
  consulNode:
    meta: 
      node: "aks0-agentless-node"

#controller:
#  enabled: true

meshGateway:
  enabled: true
  replicas: 3
  service:
    enabled: true
    type: LoadBalancer
    annotations: |
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"

ingressGateways:
  enabled: true
  defaults:
    replicas: 1
  gateways:
    - name: ingress-gateway
      service:
        type: LoadBalancer