global:
  enabled: false
  logLevel: "debug"
  name: ${cluster_name}
  datacenter: ${datacenter}
  image: "hashicorp/consul-enterprise:${consul_version}"
  imageK8S: docker.mirror.hashicorp.services/hashicorp/consul-k8s-control-plane:${consul_helm_chart_version}
  imageConsulDataplane: "hashicorp/consul-dataplane:1.0.0"

  enableConsulNamespaces: true
  adminPartitions:
    enabled: true
    name: ${partition}
  peering:
    enabled: true
  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: consul-bootstrap-acl-token
      secretKey: token
  tls:
    enabled: true
    # # Client attributes only.  Not needed for dataplane
    # enableAutoEncrypt: true
    # gossipEncryption:
    #   secretName: consul-gossip-key
    #   secretKey: gossipEncryptionKey
    # caCert:
    #   secretName: consul-ca-cert
    #   secretKey: tls.crt

externalServers:
  enabled: true
  hosts: ["${consul_external_servers}"]
  #tlsServerName: "server.${datacenter}.consul"
  httpsPort: 443
  grpcPort: 8502
  useSystemRoots: true
  k8sAuthMethodHost: ${aks_cluster}

server:
  enabled: false

connectInject:
  transparentProxy:
    defaultEnabled: true
  enabled: true
  default: true
  consulNode:
    meta: 
      node: "${cluster_name}-agentless-node"

#controller:
#  enabled: true

meshGateway:
  enabled: true
  replicas: 1
  service:
    enabled: true
    type: LoadBalancer
    # annotations: |
    #   service.beta.kubernetes.io/aws-load-balancer-type: "external"
    #   service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    #   service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"

ingressGateways:
  enabled: true
  defaults:
    replicas: 1
  gateways:
    - name: ingress-gateway
      service:
        type: LoadBalancer
        # annotations: |
        #   service.beta.kubernetes.io/aws-load-balancer-type: external