apiVersion: consul.hashicorp.com/v1alpha1
kind: PeeringAcceptor
metadata:
  name: dc2-app2 ## Destination Peer Name:  name of the peer you want to connect to
  namespace: consul     ## k8s namespace
spec:
  peer:
    secret:
      name: "peering-token-dc1-app1"
      key: "data"
      backend: "kubernetes"